# Generated by Django 4.2.20 on 2025-05-01 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon raqamingiz +998 bilan boshlanib, jami 13 ta raqamdan iborat bo‘lishi kerak. Masalan: +998901234567', regex='^\\+998(9[0-9]|3[3]|7[1])\\d{7}$')]),
        ),
    ]
