# Generated by Django 4.2.20 on 2025-05-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_alter_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='full_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='login',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
