# Generated by Django 4.2.20 on 2025-04-30 13:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Telefon raqami +998 bilan boshlanib, jami 13 ta raqamdan iborat bo‘lishi kerak (masalan: +998901234567)', regex='^\\+998\\d{9}$')])),
                ('status', models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master')], default='bachelor', max_length=100)),
                ('OTM', models.CharField(max_length=255)),
                ('separated_amount', models.BigIntegerField(default=0)),
                ('contract', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Telefon raqami +998 bilan boshlanib, jami 13 ta raqamdan iborat bo‘lishi kerak (masalan: +998901234567)', regex='^\\+998\\d{9}$')])),
                ('sponsor_amount', models.BigIntegerField()),
                ('spent_amount', models.BigIntegerField()),
                ('date', models.DateField()),
                ('payment', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('online', 'Online')], max_length=100)),
                ('user_type', models.CharField(choices=[('individual', 'Individual'), ('legal', 'Legal')], default='individual', max_length=100)),
                ('workplace', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='app1.position')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='app1.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
